language: c

os:
  - linux
  - osx
osx_image: xcode8

cache:
  ccache: true

# opt-in Ubuntu Trusty
sudo: required
dist: trusty


script:
  - cd "$TRAVIS_BUILD_DIR"
  - make
  - make test
  - make clean
