.TH mcdecrypt 1
.SH NAME
mcdecrypt \- decrypt ciphertext and recover message
.SH SYNOPSIS
.B mcdecrypt <ciphertext 8<secretkey >message
.SH DESCRIPTION
.B mcdecrypt
decrypts a ciphertext
.B ciphertext
using secretkey
.B secretkey
and recovers message
.B message
.sp
If decryption fails,
.B mcdecrypt
produces an empty output, prints an error message on stderr, and exits 100.
.SH CIPHERTEXT
240 BYTES mceliece8192128 ciphertext
.sp
n BYTES chacha20 encrypted message
.sp
16 BYTES poly1305 authenticator
.SH SECRET KEY
14080 BYTES mceliece8192128 secret key
.SH EXAMPLE
.nf
#create key\-pair
umask 077
mckeypair 5>pk 9>sk

#encrypt tarball
(cd somewhere; tar \-vjcf \- *) | mcencrypt 4<pk > data.tar.bz2.mc8

#decrypt tarball
mcdecrypt 8<sk < data.tar.bz2.mc8 | (cd somewhere; tar \-vjxf \-)
.fi
.SH SEE ALSO
.BR mckeypair (1),
.BR mcencrypt (1),
.BR https://libpqcrypto.org/command.html,
.BR https://classic.mceliece.org
