.TH mcencrypt 1
.SH NAME
mcencrypt \- encrypt message
.SH SYNOPSIS
.B mcencrypt <message 4<publickey >ciphertext
.SH DESCRIPTION
.B mcencrypt
encrypts a message
.B message 
using receivers publickey
.B publickey
and prints ciphertext
.B ciphertext
.sp
.B mcencrypt
uses post-quantum cryptographic algorithms
.B mceliece8192128
(public-key encryption),
.B chacha20
(symmetric encryption),
.B poly1305
(symmetric authentication),
.B SHA512
(hash)
.SH EXAMPLE
.nf
umask 077
mckeypair 5>pk 9>sk
echo "ahoj" | mcencrypt 4<pk | mcdecrypt 8<sk
.fi
.SH SEE ALSO
.BR mckeypair (1),
.BR mcdecrypt (1),
.BR https://libpqcrypto.org/command.html
