.TH mcencrypt 1
.SH NAME
mcencrypt \- encrypt message
.SH SYNOPSIS
.B mcencrypt <message 4<publickey >ciphertext
.SH DESCRIPTION
.B mcencrypt
encrypts a message
.B message 
using receivers publickey
.B publickey
and prints ciphertext
.B ciphertext
.SH CIPHERTEXT
240 BYTES mceliece8192128 ciphertext
.sp
n BYTES chacha20 encrypted message
.sp
16 BYTES poly1305 authenticator
.SH PUBLIC KEY
1357824 BYTES mceliece8192128 public key
.SH EXAMPLE
.nf
#create key\-pair
umask 077
mckeypair 5>pk 9>sk

#encrypt tarball
(cd somewhere; tar \-vjcf \- *) | mcencrypt 4<pk >data.tar.bz2.mc8

#decrypt tarball
mcdecrypt 8<sk <data.tar.bz2.mc8 | (cd somewhere; tar \-vjxf \-)
.fi
.SH SEE ALSO
.BR mckeypair (1),
.BR mcdecrypt (1),
.BR https://libpqcrypto.org/command.html,
.BR https://classic.mceliece.org
