.TH mckeypair 1
.SH NAME
mckeypair \- generate a key pair
.SH SYNOPSIS
.B mckeypair 5>publickey 9>secretkey
.SH DESCRIPTION
.B mckeypair
randomly generates a secret key 
.B secretkey 
and a corresponding public key
.B publickey
.SH SECRET KEY
14080 BYTES mceliece8192128 secret key
.SH PUBLIC KEY
1357824 BYTES mceliece8192128 public key
.SH EXAMPLE
.nf
#create key\-pair
umask 077
mckeypair 5>pk 9>sk

#encrypt tarball
(cd somewhere; tar \-vjcf \- *) | mcencrypt 4<pk >data.tar.bz2.mc8

#decrypt tarball
mcdecrypt 8<sk <data.tar.bz2.mc8 | (cd somewhere; tar \-vjxf \-)
.fi
.SH SEE ALSO
.BR mcencrypt (1),
.BR mcdecrypt (1),
.BR https://libpqcrypto.org/command.html,
.BR https://classic.mceliece.org
